version: '3'

services:
  #service 1: PostgresSQL Database Information
  database-postgres:
    image: postgres
    container_name: postgreSQL-service
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=asd123
      - POSTGRES_DB=authentication-server
    ports:
      - "5432:5432"
    restart: always

  #service 2: Authentication-Server Service Information
  authentication-server:
    image: authentication-server:1.0
    container_name: authentication-server
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "9090:9090"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-postgres:5432/authentication-server?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: asd123