version: '3'

services:
  #service 1: PostgresSQL Database Information
  postgres-auth-server:
    image: postgres
    container_name: postgres-auth-server
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=asd123
      - POSTGRES_DB=authentication-server
    ports:
      - "5432:5432"
    restart: always

  #service 2: Authentication-Server Service Information
  authentication-server:
    image: authentication-server:1.0
    container_name: authentication-server
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "9090:9090"
    restart: "no"
    depends_on:
      - postgres-auth-server
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: asd123
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth-server:5432/authentication-server
      spring.config.import: configserver:http://host.docker.internal:8888
      eureka.client.serviceUrl.defaultZone: http://host.docker.internal:8761/eureka