version: '3'

services:
  #service 1: PostgresSQL Database Information
  database-postgres:
    image: postgres
    container_name: postgreSQL-service
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=asd123
      - POSTGRES_DB=parcel-delivery-service
    ports:
      - "5432:5432"
    restart: always

  #service 2: ParcelDelivery Service Information
  parcel-delivery-service:
    image: parcel-delivery-service:1.0
    container_name: parcel-delivery-service
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "7070:7070"
    restart: "no"
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: asd123
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-postgres:5432/parcel-delivery-service?createDatabaseIfNotExist=true
      spring.config.import: configserver:http://host.docker.internal:8888
      spring.cloud.config.server.git.uri: configserver:http://host.docker.internal:8888
      eureka.client.serviceUrl.defaultZone: http://host.docker.internal:8761/eureka