version: '3'

services:
  #service 1: Config-Server Service Information
  eureka-server:
    image: config-server:1.0
    container_name: config-server
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    restart: on-failure